//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataStorage.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;coordinates&quot;: null,
        ///    &quot;favorited&quot;: false,
        ///    &quot;truncated&quot;: false,
        ///    &quot;created_at&quot;: &quot;Mon Sep 24 03:35:21 +0000 2012&quot;,
        ///    &quot;id_str&quot;: &quot;250075927172759552&quot;,
        ///    &quot;entities&quot;: {
        ///    &quot;urls&quot;: [
        ///
        ///    ],
        ///    &quot;hashtags&quot;: [
        ///        {
        ///        &quot;text&quot;: &quot;freebandnames&quot;,
        ///        &quot;indices&quot;: [
        ///            20,
        ///            34
        ///        ]
        ///        }
        ///    ],
        ///    &quot;user_mentions&quot;: [
        ///
        ///    ]
        ///    },
        ///    &quot;in_reply_to_user_id_str&quot;: null,
        ///    &quot;contributors&quot;: null,
        ///    &quot;text&quot;: &quot;Aggressive Ponytail #freebandna [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleTwitterJson {
            get {
                return ResourceManager.GetString("SampleTwitterJson", resourceCulture);
            }
        }
    }
}
